export const wisdom = [
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { quote: "Your limitation—it's only your imagination.", author: "Unknown" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { quote: "Great things never come from comfort zones.", author: "Unknown" },
  { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
  { quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
  { quote: "Show up, show up, show up, and after a while the muse shows up, too.", author: "Isabel Allende" },
  { quote: "This is how you do it: you sit down at the keyboard and you put one word after another until it's done. It's that easy, and that hard.", author: "Neil Gaiman" },
  { quote: "People are going to judge you all the time no matter what you do. Don't worry about other people. Worry about you.", author: "Jacqueline Woodson" },
  { quote: "Hold fast to your dreams, for if dreams die, life is a broken-winged bird that cannot fly.", author: "Langston Hughes" },
  { quote: "What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain.", author: "Maya Angelou" },
  { quote: "Never miss a good chance to shut up.", author: "Will Rogers" },
  { quote: "We cannot change the cards we are dealt, just how we play the hand.", author: "Randy Pausch" },
  { quote: "Never ruin an apology with an excuse.", author: "Benjamin Franklin" },
  { quote: "Don't expect others to listen to your advice and ignore your example.", author: "H. Jackson Brown, Jr." },
  { quote: "In giving advice I advise you, be short.", author: "Horace" },
  { quote: "Start writing, no matter what. The water does not flow until the faucet is turned on.", author: "Louis L'Amour" },
  { quote: "You can always edit a bad page. You can't edit a blank page.", author: "Jodi Picoult" },
  { quote: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { quote: "The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks, and then starting on the first one.", author: "Mark Twain" },
  { quote: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen Covey" },
];

export const starters = [
  "What’s the best thing that happened to you this week?",
  "What’s your favorite way to spend a day off?",
  "What’s one thing you’re really good at?",
  "What’s your favorite thing to do with your friends?",
  "What’s the most interesting thing you’ve learned recently?",
  "Hey, I noticed your [book/shirt/shoes]. Where did you get it?",
  "Excuse me, do you know if [place/event detail] is around here?",
  "Hi, I’m trying to settle a debate — what’s your take on [light topic]?",
  "Hey, I like your energy — mind if I join the conversation?",
  "Hi, I’m [name]. What’s your favorite part about [current setting]?",
  "Excuse me, I saw you laughing and wanted to ask what’s so funny?",
  "Hey, do you come here often, or is this a first-time adventure?",
  "Hi, I couldn’t help but notice your [accessory/item] — that’s unique!",
  "Hey, quick question — do you know how [practical/local thing] works here?",
  "Hi, I’m doing a quick social experiment — can I ask a fun question?",
];

export const motivations = [
  { quote: "Pain is weakness leaving the body.", author: "Chesty Puller" },
  { quote: "Success is not for the lazy.", author: "Unknown" },
  { quote: "Don’t stop when you’re tired. Stop when you’re done.", author: "David Goggins" },
  { quote: "Wake up with determination. Go to bed with satisfaction.", author: "George Horace Lorimer" },
  { quote: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { quote: "Little things make big days.", author: "Unknown" },
  { quote: "It’s going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { quote: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
  { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
  { quote: "Dream bigger. Do bigger.", author: "Unknown" },
  { quote: "Don’t wait for opportunity. Create it.", author: "George Bernard Shaw" },
  { quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
  { quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { quote: "Dream it. Believe it. Build it.", author: "Unknown" },
  { quote: "Success is what comes after you stop making excuses.", author: "Grant Cardone" },
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
];

export const mantras = [
  "I own my time and prioritize what moves me forward.",
  "I execute plans with discipline and precision.",
  "I attract opportunities through action, not wishful thinking.",
  "I embrace challenges — they sharpen my edge.",
  "I maintain clarity under pressure.",
  "I control my habits, they do not control me.",
  "I act decisively when most hesitate.",
  "I surround myself with people who elevate me.",
  "I leverage my strengths relentlessly.",
  "I speak with purpose and follow through.",
  "I grow from feedback, not excuses.",
  "I set high standards and meet them daily.",
  "I manage energy, not just time.",
  "I maintain resilience when outcomes are uncertain.",
  "I value results over recognition.",
  "I learn faster than I fail.",
  "I focus on influence, not approval.",
  "I choose action over comfort.",
  "I visualize goals, then execute methodically.",
  "I remain composed when others panic.",
  "I embrace responsibility and avoid blame.",
  "I measure progress, not perfection.",
  "I persist while others quit.",
  "I plan, execute, and reflect consistently.",
  "I cultivate presence and project confidence.",
  "I adapt without losing principles.",
  "I prioritize health as leverage for success.",
  "I invest in skills that compound value.",
  "I communicate clearly and assert boundaries.",
  "I attract high-value situations through preparation.",
  "I control focus and ignore distractions.",
  "I commit fully and finish what I start.",
  "I act on intuition backed by reason.",
  "I maintain integrity in small and large decisions.",
  "I dominate my inner critic, not my goals.",
  "I cultivate patience alongside urgency.",
  "I turn obstacles into leverage.",
  "I act first, evaluate later when necessary.",
  "I create leverage by helping others succeed.",
  "I remain hungry, disciplined, and unapologetic.",
];

export const prompts = [
  "Describe something you’re grateful for right now.",
  "What are three things you can see from where you are?",
  "Focus on your breath for one minute. How do you feel?",
  "What is one thing you can do to be kind to yourself today?",
  "Listen to the sounds around you. What do you hear?",
  "Hold eye contact two seconds longer than usual.",
  "Smile first — it rewires your confidence instantly.",
  "Say hi like you’ve already met.",
  "Lean in slightly when speaking, shows intent.",
  "Ask her opinion — confidence is curiosity.",
  "Don’t fill silences — let her chase the next word.",
  "Compliment something uncommon, not obvious.",
  "Stand tall, slow your movements.",
  "Pause before answering — power in stillness.",
  "Speak slightly slower than normal — calm signals control.",
  "Own your space — don’t shrink.",
  "Don’t rush — time bends for confidence.",
  "Ask her name, repeat it once, remember it.",
  "Smile with your eyes, not just your mouth.",
  "Adjust posture before walking up — signal readiness.",
  "Don’t rehearse lines — respond to reality.",
  "Let her talk, study her phrasing.",
  "Ask a light question, then listen fully.",
  "Drop your voice half a tone lower — subtle authority.",
  "Hold your drink steady — microconfidence cue.",
  "Mirror energy, not words.",
  "Stay still when others fidget.",
  "Don’t explain your jokes — own them.",
  "Use open palms when gesturing.",
  "Don’t chase approval — project ease.",
  "Ask for her story, not her job.",
  "Keep sentences short, direct.",
  "Laugh slowly, not loudly.",
  "Don’t fill the pause — let tension build.",
  "Take a half-step closer when she leans in.",
  "Use silence as punctuation.",
  "Make the first move without justification.",
  "Keep your phone away — full focus wins.",
  "Notice details, comment once, move on.",
  "Never self-correct mid-sentence — finish clean.",
  "Don’t overexplain — clarity beats detail.",
  "End the chat first, leave her curious.",
  "Walk away slow, not abrupt.",
  "Re-engage later like it’s continuation, not restart.",
  "Confidence is absence of rush — act accordingly.",
];