export const wisdom = [
  { key: "wisdom.quote1", author: "Chinese Proverb" },
  { key: "wisdom.quote2", author: "Unknown" },
  { key: "wisdom.quote3", author: "Unknown" },
  { key: "wisdom.quote4", author: "Unknown" },
  { key: "wisdom.quote5", author: "Unknown" },
  { key: "wisdom.quote6", author: "Unknown" },
  { key: "wisdom.quote7", author: "Isabel Allende" },
  { key: "wisdom.quote8", author: "Neil Gaiman" },
  { key: "wisdom.quote9", author: "Jacqueline Woodson" },
  { key: "wisdom.quote10", author: "Langston Hughes" },
  { key: "wisdom.quote11", author: "Maya Angelou" },
  { key: "wisdom.quote12", author: "Will Rogers" },
  { key: "wisdom.quote13", author: "Randy Pausch" },
  { key: "wisdom.quote14", author: "Benjamin Franklin" },
  { key: "wisdom.quote15", author: "H. Jackson Brown, Jr." },
  { key: "wisdom.quote16", author: "Horace" },
  { key: "wisdom.quote17", author: "Louis L'Amour" },
  { key: "wisdom.quote18", author: "Jodi Picoult" },
  { key: "wisdom.quote19", author: "Maya Angelou" },
  { key: "wisdom.quote20", author: "Mark Twain" },
  { key: "wisdom.quote21", author: "Stephen Covey" },
];

export const starters = [
  "starters.item1",
  "starters.item2",
  "starters.item3",
  "starters.item4",
  "starters.item5",
  "starters.item6",
  "starters.item7",
  "starters.item8",
  "starters.item9",
  "starters.item10",
  "starters.item11",
  "starters.item12",
  "starters.item13",
  "starters.item14",
  "starters.item15",
];

export const motivations = [
  { key: "motivations.quote1", author: "Chesty Puller" },
  { key: "motivations.quote2", author: "Unknown" },
  { key: "motivations.quote3", author: "David Goggins" },
  { key: "motivations.quote4", author: "George Horace Lorimer" },
  { key: "motivations.quote5", author: "Sean Patrick Flanery" },
  { key: "motivations.quote6", author: "Unknown" },
  { key: "motivations.quote7", author: "Unknown" },
  { key: "motivations.quote8", author: "Unknown" },
  { key: "motivations.quote9", author: "Unknown" },
  { key: "motivations.quote10", author: "Unknown" },
  { key: "motivations.quote11", author: "George Bernard Shaw" },
  { key: "motivations.quote12", author: "Unknown" },
  { key: "motivations.quote13", author: "Unknown" },
  { key: "motivations.quote14", author: "Unknown" },
  { key: "motivations.quote15", author: "Grant Cardone" },
  { key: "motivations.quote16", author: "Steve Jobs" },
  { key: "motivations.quote17", author: "Theodore Roosevelt" },
  { key: "motivations.quote18", author: "Eleanor Roosevelt" },
  { key: "motivations.quote19", author: "Mark Twain" },
  { key: "motivations.quote20", author: "Sam Levenson" },
];

export const mantras = [
  "mantras.item1",
  "mantras.item2",
  "mantras.item3",
  "mantras.item4",
  "mantras.item5",
  "mantras.item6",
  "mantras.item7",
  "mantras.item8",
  "mantras.item9",
  "mantras.item10",
  "mantras.item11",
  "mantras.item12",
  "mantras.item13",
  "mantras.item14",
  "mantras.item15",
  "mantras.item16",
  "mantras.item17",
  "mantras.item18",
  "mantras.item19",
  "mantras.item20",
  "mantras.item21",
  "mantras.item22",
  "mantras.item23",
  "mantras.item24",
  "mantras.item25",
  "mantras.item26",
  "mantras.item27",
  "mantras.item28",
  "mantras.item29",
  "mantras.item30",
  "mantras.item31",
  "mantras.item32",
  "mantras.item33",
  "mantras.item34",
  "mantras.item35",
  "mantras.item36",
  "mantras.item37",
  "mantras.item38",
  "mantras.item39",
  "mantras.item40",
];

export const prompts = [
  "prompts.item1",
  "prompts.item2",
  "prompts.item3",
  "prompts.item4",
  "prompts.item5",
  "prompts.item6",
  "prompts.item7",
  "prompts.item8",
  "prompts.item9",
  "prompts.item10",
  "prompts.item11",
  "prompts.item12",
  "prompts.item13",
  "prompts.item14",
  "prompts.item15",
  "prompts.item16",
  "prompts.item17",
  "prompts.item18",
  "prompts.item19",
  "prompts.item20",
  "prompts.item21",
  "prompts.item22",
  "prompts.item23",
  "prompts.item24",
  "prompts.item25",
  "prompts.item26",
  "prompts.item27",
  "prompts.item28",
  "prompts.item29",
  "prompts.item30",
  "prompts.item31",
  "prompts.item32",
  "prompts.item33",
  "prompts.item34",
  "prompts.item35",
  "prompts.item36",
  "prompts.item37",
  "prompts.item38",
  "prompts.item39",
  "prompts.item40",
  "prompts.item41",
  "prompts.item42",
  "prompts.item43",
  "prompts.item44",
  "prompts.item45",
];
